
platform :ios, '8.0'
use_frameworks!

target 'Feed Me' do
pod 'SwiftyJSON'
pod 'GoogleMaps'
pod 'SAParallaxViewControllerSwift'
pod 'ObjectMapper'
pod 'SDWebImage'
pod 'Alamofire'
pod 'MSTwitterSplashScreen'
end

